const fs = require('fs');
let c = fs.readFileSync('views/budget.ejs', 'utf8');

const calendarModalHtml = `\n    <!-- ===== MODAL KALENDER UNTUK BUAT ULANG ===== -->\n    <div id="recreateDateModal" style="display:none; position:fixed; top:0; left:0; width:100vw; height:100vh; background:rgba(15,23,42,0.7); backdrop-filter:blur(4px); z-index:999999; align-items:center; justify-content:center;">\n        <div style="background:var(--card-bg); padding:24px; border-radius:16px; width:90%; max-width:400px; box-shadow:0 25px 50px -12px rgba(0,0,0,0.25);">\n            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;">\n                <h3 style="margin:0; font-size:1.2rem; color:var(--text-primary);"><i class="fas fa-calendar-alt" style="color:var(--primary); margin-right:8px;"></i> Pilih Rentang Waktu</h3>\n                <button type="button" onclick="closeRecreateDateModal()" style="background:transparent; border:none; font-size:1.2rem; color:var(--text-muted); cursor:pointer;"><i class="fas fa-times"></i></button>\n            </div>\n            <div style="display:flex; flex-direction:column; gap:16px;">\n                <div>\n                    <label style="display:block; margin-bottom:8px; font-size:0.9rem; font-weight:600; color:var(--text-secondary);">Tanggal Mulai</label>\n                    <input type="date" id="recreateModalStartDate" class="form-input" style="width:100%;">\n                </div>\n                <div>\n                    <label style="display:block; margin-bottom:8px; font-size:0.9rem; font-weight:600; color:var(--text-secondary);">Tanggal Berakhir</label>\n                    <input type="date" id="recreateModalEndDate" class="form-input" style="width:100%;">\n                </div>\n            </div>\n            <div style="display:flex; gap:12px; margin-top:24px;">\n                <button type="button" onclick="closeRecreateDateModal()" style="flex:1; padding:12px; border-radius:8px; border:1px solid var(--border); background:transparent; color:var(--text-secondary); font-weight:600; cursor:pointer;">Batal</button>\n                <button type="button" onclick="applyRecreateDateRange()" style="flex:1; padding:12px; border-radius:8px; border:none; background:var(--primary); color:white; font-weight:600; cursor:pointer;">Terapkan</button>\n            </div>\n        </div>\n    </div>\n\n`;

// Insert before </body>
c = c.replace('</body>', calendarModalHtml + '</body>');
fs.writeFileSync('views/budget.ejs', c);
console.log('done');
